export type { AnimationConfig } from './motionVariants';

export {
  GROUNDING_ANIMATION,
  UNFOLDING_ANIMATION,
  REASSURANCE_ANIMATION,
  VOW_ANIMATION,
  EVERYDAY_ANIMATION,
  ANCHOR_ANIMATION,
  EASE_OUT_QUART,
  EASE_OUT_CUBIC,
  createTextVariants,
  standardTextVariants,
  reflectiveTextVariants,
  reassuranceTextVariants,
  vowTextVariants,
  everydayTextVariants,
  anchorTextVariants,
  fadeInVariants,
  calculateStaggerDelay,
  calculateGroundingDelay,
  calculateUnfoldingDelay,
  calculateReassuranceDelay,
  calculateVowDelay,
  calculateEverydayDelay,
  calculateAnchorDelay,
} from './motionVariants';
